=== nandaTF/svnroot/TRUNK/sernet.gs.server/WebContent/WEB-INF/hitro.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

  XML Schema for Hitro-UI.
  
  Author:  <koderman@sernet.de>
  

  Hitro is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Hitro is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Hitro; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/-->

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
		   xmlns:hitro="http://www.sernet.de/hitro"
           targetNamespace='http://www.sernet.de/hitro'
           elementFormDefault="qualified"
>



<!-- The root node for all possible documentation properties. 
     List of entities.
-->
<xs:element name="huientities">
<xs:complexType>
      <xs:sequence>
      	<xs:element name="huientity" 
                  type="hitro:huientitytype"
                  minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
</xs:complexType>
</xs:element>


<!-- 
		One entity with all its properties.
 -->
<xs:complexType name="huientitytype">
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
	     		<xs:element  name="huiproperty" 
                  		type="hitro:huipropertytype"
                 		minOccurs="0" maxOccurs="unbounded" />
	           	<xs:element  name="huipropertygroup" 
                  		type="hitro:huipropertygrouptype"
                 		minOccurs="0" maxOccurs="unbounded" />

	</xs:sequence>
	<xs:attribute name="id" type="xs:ID" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>


<!--
Group of properties, may have dependencies, which means it will only
be displayed when one of the given options has been previously selected.
-->
<xs:complexType name="huipropertygrouptype">
	<xs:sequence>
        <xs:element  name="depends" 
			type="hitro:dependstype"
		    minOccurs="0" maxOccurs="unbounded"/>
		    
		<xs:element  name="huiproperty" 
                  		type="hitro:huipropertytype"
                 		minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>

	<xs:attribute name="id" type="xs:ID" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="columns" type="xs:int" default="1" />
</xs:complexType>
    
<xs:complexType name="dependstype">
	<xs:attribute name="option" type="xs:IDREF" />
</xs:complexType>

<xs:complexType name="referencestype">
	<xs:attribute name="entitytype" type="xs:IDREF" />
</xs:complexType>
	    	
<!-- 
  A property to be documented.

  May have dependencies, which means it will only
  be displayed when one of the given options has been previously selected.

  Attributes:
  name:        name of property, i.e. "Colour"
  enum:        free text entry, or selection of fixed options?
  multiselect: can user select multiple items at once?
/-->
<xs:complexType name="huipropertytype">   
    
    <xs:sequence>
    	<xs:element name="depends" 
        			type="hitro:dependstype"
        		    minOccurs="0" maxOccurs="unbounded"/>
        		    
        <xs:element name="references" 
        			type="hitro:referencestype"
        		    minOccurs="0" maxOccurs="1"/>
        		    
        <xs:element name="defaultRule" minOccurs="0" maxOccurs="1">
        	<xs:complexType>
        	<xs:sequence>
        		<xs:element name="param" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        	</xs:sequence>
        	  <xs:attribute name="class" type="xs:string" use="required"/>
        	</xs:complexType>
        </xs:element>

        <xs:element name="validationRule" minOccurs="0" maxOccurs="unbounded">
        	<xs:complexType>
        	<xs:sequence>
        		<xs:element name="param" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        	</xs:sequence>
        	  <xs:attribute name="class" type="xs:string" use="required"/>
        	</xs:complexType>
        </xs:element>

        
        <!--
          Unlimited list of options for enum type, 
          i.e. "beige, black, blue..."
          
          Attributes:
          id:        unique id under which this entry is referenced 
                     in the database
          name:      text to appear in drop-down lists etc.
        /-->
	  <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
	      <xs:complexType>
	          <xs:attribute name="id" type="xs:ID" use="required"/>
	          <xs:attribute name="name" type="xs:string" use="required"/>
	      </xs:complexType>
	  </xs:element>            
        
    </xs:sequence>
        
    <xs:attribute name="id" type="xs:ID" use="required"/>
    
    <xs:attribute name="name" type="xs:string" use="required"/>

	<!-- Tooltip hint to display in GUI -->    
    <xs:attribute name="tooltip" type="xs:string"/>
    
    <!-- How to edit this property: -->
   	<xs:attribute name="inputtype" type="hitro:inputtypes" default="line"/>
	
	<!-- Optional or required property? -->
	<xs:attribute name="required" type="xs:boolean" default="false"/> 
	
	<!-- Has initial focus? -->
	<xs:attribute name="focus" type="xs:boolean" default="false"/> 
	
	<!-- Field containsURL? User can click on it. -->
	<xs:attribute name="isURL" type="xs:boolean" default="false"/> 

	<!-- Is editable? -->
	<xs:attribute name="editable" type="xs:boolean" default="true"/> 
    
	<!-- Is visible in GUI? -->
	<xs:attribute name="visible" type="xs:boolean" default="true"/> 
</xs:complexType>

<xs:simpleType name="inputtypes" >
	<xs:restriction base="xs:string">
	<xs:enumeration value="line"/>
	<xs:enumeration value="singleoption"/>
	<xs:enumeration value="multioption"/>
	<xs:enumeration value="text"/>
	<xs:enumeration value="reference"/>
	<xs:enumeration value="date"/>
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== nandaTF/svnroot/TRUNK/sernet.gs.ui.rcp.main/conf/SNCA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	
    
	Definition of properties and predefined options for Hitro-UI.
	
	A dynamic object model is generated based on the definitions 
	in this file and the necessary GUI forms created to allow 
	selection of or entering data.
	
	Concrete selections or values entered by the user will be saved in the 
	database.
	
    Author:  <koderman@sernet.de>
-->

<!--
Template:

<huientity
    name=""
    id="">
    <huiproperty
        name=""
        id=""/>
</huientity>

-->

<huientities
	xmlns="http://www.sernet.de/hitro"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sernet.de/hitro hitro.xsd">

 <huientity
        name="Raum"
        id="raum">
        <huiproperty
            name="Kürzel"
            id="raum_kuerzel"
            focus="true" >
             <defaultRule class="SimpleValue">
                	<param>R-</param>
                </defaultRule>
        </huiproperty>
        <huiproperty
            name="Name"
            id="raum_name" />

        <huiproperty
            id="raum_tag"
            name="Tags"
            tooltip="Liste von Tags, getrennt durch Komma oder Leerzeichen"
        />
        
        <huiproperty
            name="Anzahl"
            id="raum_anzahl" />
        <huiproperty
            name="Erläuterung"
            inputtype="text"
            id="raum_erlaeuterung" />
            
        <huipropertygroup
			id="raum_group_schutzbedarf"
			name="Schutzbedarf">
			<huiproperty
				id="raum_vertraulichkeit"
				name="Vertraulichkeit"
				inputtype="singleoption">
				<option
					id="raum_vertraulichkeit_normal"
					name="Normal" />
				<option
					id="raum_vertraulichkeit_hoch"
					name="Hoch" />
				<option
					id="raum_vertraulichkeit_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>
			<huiproperty
				id="raum_verfuegbarkeit"
				name="Verfügbarkeit"
				inputtype="singleoption">
				<option
					id="raum_verfuegbarkeit_normal"
					name="Normal" />
				<option
					id="raum_verfuegbarkeit_hoch"
					name="Hoch" />
				<option
					id="raum_verfuegbarkeit_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>
			<huiproperty
				id="raum_integritaet"
				name="Integrität"
				inputtype="singleoption">
				<option
					id="raum_integritaet_normal"
					name="Normal" />
				<option
					id="raum_integritaet_hoch"
					name="Hoch" />
				<option
					id="raum_integritaet_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>

			<huiproperty
				name="Begründung Vertraulichkeit"
				id="raum_vertraulichkeit_begruendung" />
			<huiproperty
				name="Begründung Verfügbarkeit"
				id="raum_verfuegbarkeit_begruendung" />
			<huiproperty
				name="Begründung Integrität"
				id="raum_integritaet_begruendung" />
				
			
		</huipropertygroup>
		
		<huipropertygroup 
			name="Managementbewertung" 
			id="raum_mgmtreview">
			<huiproperty 
				name="Erg. Sicherheitsanalyse" 
				id="raum_ergaenzendeanalyse"
				inputtype="singleoption">
				<option 
					id="raum_ergaenzendeanalyse_schutzbedarf" 
					name="lt. Schutzbedarf"/>
				<option 
					id="raum_ergaenzendeanalyse_modell" 
					name="zusätzlich vormerken"/>
			</huiproperty>
			
			<huiproperty 
				name="Risikoanalyse" 
				id="raum_risikoanalyse"
				inputtype="singleoption">
				<option 
					id="raum_risikoanalyse_noetig" 
					name="nötig"/>
				<option 
					id="raum_risikoanalyse_unnoetig" 
					name="entbehrlich"/>
			</huiproperty>
			
			<huiproperty 
				name="Begründung Mgmt" 
				id="raum_risikoanalyse_begruendung"
				inputtype="text"/>
			
		</huipropertygroup>
		
    </huientity>

 <huientity
        name="Server"
        id="server">
        <huiproperty
            name="Kürzel"
            id="server_kuerzel"
            focus="true" >
             <defaultRule class="SimpleValue">
                	<param>S-</param>
                </defaultRule>
        </huiproperty>
        <huiproperty
            name="Name"
            id="server_name" />

        <huiproperty
            id="server_tag"
            name="Tags"
            tooltip="Liste von Tags, getrennt durch Komma oder Leerzeichen"
        />

            
        <huiproperty
            name="Anzahl"
            id="server_anzahl" />
        <huiproperty
            name="Erläuterung"
            inputtype="text"
            id="server_erlaeuterung" />
        <huiproperty
            name="Plattform"
            id="server_plattform" />
        <huiproperty
            name="Aufstellungsort"
            id="server_aufstellungsort" />
        <huiproperty
            name="Status"
            id="server_status"
            inputtype="singleoption">
                <option
                    id="server_status_betrieb"
                    name="Betrieb" />
                <option
                    id="server_status_planung"
                    name="Planung" />
                <option
                    id="server_status_grundinstallation"
                    name="Grundinstallation" />
                <option
                    id="server_status_Konfiguration"
                    name="Konfiguration" />
                <option
                    id="server_status_test"
                    name="Test" />
                <option
                    id="server_status_auslieferung"
                    name="Auslieferung" />
                <option
                    name="Reparatur"
                    id="server_status_reparatur" />
                <option
                    name="Standby"
                    id="server_status_standby" />
                <option
                    name="Reserve"
                    id="server_status_reserve" />
        </huiproperty>
        <huiproperty
            name="Anwender"
            id="server_anwender" />
        <huiproperty
            name="Admin"
            id="server_admin" />
        <huiproperty
            name="Netzadressen"
            id="server_netadr" />
		<huipropertygroup
			id="server_group_schutzbedarf"
			name="Schutzbedarf">
			<huiproperty
				id="server_vertraulichkeit"
				name="Vertraulichkeit"
				inputtype="singleoption">
				<option
					id="server_vertraulichkeit_normal"
					name="Normal" />
				<option
					id="server_vertraulichkeit_hoch"
					name="Hoch" />
				<option
					id="server_vertraulichkeit_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>
			<huiproperty
				id="server_verfuegbarkeit"
				name="Verfügbarkeit"
				inputtype="singleoption">
				<option
					id="server_verfuegbarkeit_normal"
					name="Normal" />
				<option
					id="server_verfuegbarkeit_hoch"
					name="Hoch" />
				<option
					id="server_verfuegbarkeit_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>
			<huiproperty
				id="server_integritaet"
				name="Integrität"
				inputtype="singleoption">
				<option
					id="server_integritaet_normal"
					name="Normal" />
				<option
					id="server_integritaet_hoch"
					name="Hoch" />
				<option
					id="server_integritaet_sehrhoch"
					name="Sehr Hoch" />
			</huiproperty>

			<huiproperty
				name="Begründung Vertraulichkeit"
				id="server_vertraulichkeit_begruendung" />
			<huiproperty
				name="Begründung Verfügbarkeit"
				id="server_verfuegbarkeit_begruendung" />
			<huiproperty
				name="Begründung Integrität"
				id="server_integritaet_begruendung" />

		</huipropertygroup>        
		<huipropertygroup 
			name="Managementbewertung" 
			id="server_mgmtreview">
			<huiproperty 
				name="Erg. Sicherheitsanalyse" 
				id="server_ergaenzendeanalyse"
				inputtype="singleoption">
				<option 
					id="server_ergaenzendeanalyse_schutzbedarf" 
					name="lt. Schutzbedarf"/>
				<option 
					id="server_ergaenzendeanalyse_modell" 
					name="zusätzlich vormerken"/>
			</huiproperty>
			
			<huiproperty 
				name="Risikoanalyse" 
				id="server_risikoanalyse"
				inputtype="singleoption">
				<option 
					id="server_risikoanalyse_noetig" 
					name="nötig"/>
				<option 
					id="server_risikoanalyse_unnoetig" 
					name="entbehrlich"/>
			</huiproperty>
			
			<huiproperty 
				name="Begründung Mgmt" 
				id="server_risikoanalyse_begruendung"
				inputtype="text"/>
			
		</huipropertygroup>   
    </huientity>

    <huientity
        name="TK-Komponente"
        id="tkkomponente">
        <huiproperty
            name="Kürzel"
            id="tkkomponente_kuerzel"
            focus="true" >
             <defaultRule class="SimpleValue">
                	<param>TK-</param>
                </defaultRule>
        </huiproperty>
        <huiproperty
            name="Name"
            id="tkkomponente_name" />
            
        <huiproperty
            id="tkkomponente_tag"
            name="Tags"
            tooltip="Liste von Tags, getrennt durch Komma oder Leerzeichen"
        />

            
        <huiproperty
            name="Anzahl"
            id="tkkomponente_anzahl" />
        <huiproperty
            name="Erläuterung"
            inputtype="text"
            id="tkkomponente_erlaeuterung" />
        <huiproperty
            name="Plattform"
            id="tkkomponente_plattform" />
        <huiproperty
            name="Aufstellungsort"
            id="tkkomponente_aufstellungsort" />
        <huiproperty
            name="Status"
            id="tkkomponente_status"
            inputtype="singleoption">
                <option
                    id="tkkomponente_status_betrieb"
                    name="Betrieb" />
                <option
                    id="tkkomponente_status_planung"
                    name="Planung" />
                <option
                    id="tkkomponente_status_grundinstallation"
                    name="Grundinstallation" />
                <option
                    id="tkkomponente_status_Konfiguration"
                    name="Konfiguration" />
                <option
                    id="tkkomponente_status_test"
                    name="Test" />
                <option
